### ISSUE TITLE
Doesnt work on synapse x 3.0

### ISSUE THREAD

**Issue by antgame11** [exxtremestuffs/SimpleSpySource#16]
when I did rspy in inf yield it didnt work pls fix this

**Comment by ghost** [comment]
Synapse X 3.0 is not released.

You should determine the methods that are unavailable to you and report them to Synapse Support.

**Comment by RealPacket** [comment]
just use simple spy v3 (or v2 idk if it works) lol

**Comment by antgame11** [comment]
Why the fuck are you commenting on an ancient issue, fuck off
